shim ! (MaaTaskerCreate () -> * mut MaaTasker) ;
shim ! (MaaTaskerDestroy (tasker : * mut MaaTasker) -> ()) ;
shim ! (MaaTaskerAddSink (tasker : * mut MaaTasker , sink : MaaEventCallback , trans_arg : * mut :: std :: os :: raw :: c_void) -> MaaSinkId) ;
shim ! (MaaTaskerRemoveSink (tasker : * mut MaaTasker , sink_id : MaaSinkId) -> ()) ;
shim ! (MaaTaskerClearSinks (tasker : * mut MaaTasker) -> ()) ;
shim ! (MaaTaskerAddContextSink (tasker : * mut MaaTasker , sink : MaaEventCallback , trans_arg : * mut :: std :: os :: raw :: c_void) -> MaaSinkId) ;
shim ! (MaaTaskerRemoveContextSink (tasker : * mut MaaTasker , sink_id : MaaSinkId) -> ()) ;
shim ! (MaaTaskerClearContextSinks (tasker : * mut MaaTasker) -> ()) ;
shim ! (MaaTaskerSetOption (tasker : * mut MaaTasker , key : MaaTaskerOption , value : MaaOptionValue , val_size : MaaOptionValueSize) -> MaaBool) ;
shim ! (MaaTaskerBindResource (tasker : * mut MaaTasker , res : * mut MaaResource) -> MaaBool) ;
shim ! (MaaTaskerBindController (tasker : * mut MaaTasker , ctrl : * mut MaaController) -> MaaBool) ;
shim ! (MaaTaskerInited (tasker : * const MaaTasker) -> MaaBool) ;
shim ! (MaaTaskerPostTask (tasker : * mut MaaTasker , entry : * const :: std :: os :: raw :: c_char , pipeline_override : * const :: std :: os :: raw :: c_char) -> MaaTaskId) ;
shim ! (MaaTaskerPostRecognition (tasker : * mut MaaTasker , reco_type : * const :: std :: os :: raw :: c_char , reco_param : * const :: std :: os :: raw :: c_char , image : * const MaaImageBuffer) -> MaaTaskId) ;
shim ! (MaaTaskerPostAction (tasker : * mut MaaTasker , action_type : * const :: std :: os :: raw :: c_char , action_param : * const :: std :: os :: raw :: c_char , box_ : * const MaaRect , reco_detail : * const :: std :: os :: raw :: c_char) -> MaaTaskId) ;
shim ! (MaaTaskerStatus (tasker : * const MaaTasker , id : MaaTaskId) -> MaaStatus) ;
shim ! (MaaTaskerWait (tasker : * const MaaTasker , id : MaaTaskId) -> MaaStatus) ;
shim ! (MaaTaskerRunning (tasker : * const MaaTasker) -> MaaBool) ;
shim ! (MaaTaskerPostStop (tasker : * mut MaaTasker) -> MaaTaskId) ;
shim ! (MaaTaskerStopping (tasker : * const MaaTasker) -> MaaBool) ;
shim ! (MaaTaskerGetResource (tasker : * const MaaTasker) -> * mut MaaResource) ;
shim ! (MaaTaskerGetController (tasker : * const MaaTasker) -> * mut MaaController) ;
shim ! (MaaTaskerClearCache (tasker : * mut MaaTasker) -> MaaBool) ;
shim ! (MaaTaskerOverridePipeline (tasker : * mut MaaTasker , task_id : MaaTaskId , pipeline_override : * const :: std :: os :: raw :: c_char) -> MaaBool) ;
shim ! (MaaTaskerGetRecognitionDetail (tasker : * const MaaTasker , reco_id : MaaRecoId , node_name : * mut MaaStringBuffer , algorithm : * mut MaaStringBuffer , hit : * mut MaaBool , box_ : * mut MaaRect , detail_json : * mut MaaStringBuffer , raw : * mut MaaImageBuffer , draws : * mut MaaImageListBuffer) -> MaaBool) ;
shim ! (MaaTaskerGetActionDetail (tasker : * const MaaTasker , action_id : MaaActId , node_name : * mut MaaStringBuffer , action : * mut MaaStringBuffer , box_ : * mut MaaRect , success : * mut MaaBool , detail_json : * mut MaaStringBuffer) -> MaaBool) ;
shim ! (MaaTaskerGetNodeDetail (tasker : * const MaaTasker , node_id : MaaNodeId , node_name : * mut MaaStringBuffer , reco_id : * mut MaaRecoId , action_id : * mut MaaActId , completed : * mut MaaBool) -> MaaBool) ;
shim ! (MaaTaskerGetTaskDetail (tasker : * const MaaTasker , task_id : MaaTaskId , entry : * mut MaaStringBuffer , node_id_list : * mut MaaNodeId , node_id_list_size : * mut MaaSize , status : * mut MaaStatus) -> MaaBool) ;
shim ! (MaaTaskerGetLatestNode (tasker : * const MaaTasker , node_name : * const :: std :: os :: raw :: c_char , latest_id : * mut MaaNodeId) -> MaaBool) ;
shim ! (MaaResourceCreate () -> * mut MaaResource) ;
shim ! (MaaResourceDestroy (res : * mut MaaResource) -> ()) ;
shim ! (MaaResourceAddSink (res : * mut MaaResource , sink : MaaEventCallback , trans_arg : * mut :: std :: os :: raw :: c_void) -> MaaSinkId) ;
shim ! (MaaResourceRemoveSink (res : * mut MaaResource , sink_id : MaaSinkId) -> ()) ;
shim ! (MaaResourceClearSinks (res : * mut MaaResource) -> ()) ;
shim ! (MaaResourceRegisterCustomRecognition (res : * mut MaaResource , name : * const :: std :: os :: raw :: c_char , recognition : MaaCustomRecognitionCallback , trans_arg : * mut :: std :: os :: raw :: c_void) -> MaaBool) ;
shim ! (MaaResourceUnregisterCustomRecognition (res : * mut MaaResource , name : * const :: std :: os :: raw :: c_char) -> MaaBool) ;
shim ! (MaaResourceClearCustomRecognition (res : * mut MaaResource) -> MaaBool) ;
shim ! (MaaResourceRegisterCustomAction (res : * mut MaaResource , name : * const :: std :: os :: raw :: c_char , action : MaaCustomActionCallback , trans_arg : * mut :: std :: os :: raw :: c_void) -> MaaBool) ;
shim ! (MaaResourceUnregisterCustomAction (res : * mut MaaResource , name : * const :: std :: os :: raw :: c_char) -> MaaBool) ;
shim ! (MaaResourceClearCustomAction (res : * mut MaaResource) -> MaaBool) ;
shim ! (MaaResourcePostBundle (res : * mut MaaResource , path : * const :: std :: os :: raw :: c_char) -> MaaResId) ;
shim ! (MaaResourcePostOcrModel (res : * mut MaaResource , path : * const :: std :: os :: raw :: c_char) -> MaaResId) ;
shim ! (MaaResourcePostPipeline (res : * mut MaaResource , path : * const :: std :: os :: raw :: c_char) -> MaaResId) ;
shim ! (MaaResourcePostImage (res : * mut MaaResource , path : * const :: std :: os :: raw :: c_char) -> MaaResId) ;
shim ! (MaaResourceOverridePipeline (res : * mut MaaResource , pipeline_override : * const :: std :: os :: raw :: c_char) -> MaaBool) ;
shim ! (MaaResourceOverrideNext (res : * mut MaaResource , node_name : * const :: std :: os :: raw :: c_char , next_list : * const MaaStringListBuffer) -> MaaBool) ;
shim ! (MaaResourceOverrideImage (res : * mut MaaResource , image_name : * const :: std :: os :: raw :: c_char , image : * const MaaImageBuffer) -> MaaBool) ;
shim ! (MaaResourceGetNodeData (res : * mut MaaResource , node_name : * const :: std :: os :: raw :: c_char , buffer : * mut MaaStringBuffer) -> MaaBool) ;
shim ! (MaaResourceClear (res : * mut MaaResource) -> MaaBool) ;
shim ! (MaaResourceStatus (res : * const MaaResource , id : MaaResId) -> MaaStatus) ;
shim ! (MaaResourceWait (res : * const MaaResource , id : MaaResId) -> MaaStatus) ;
shim ! (MaaResourceLoaded (res : * const MaaResource) -> MaaBool) ;
shim ! (MaaResourceSetOption (res : * mut MaaResource , key : MaaResOption , value : MaaOptionValue , val_size : MaaOptionValueSize) -> MaaBool) ;
shim ! (MaaResourceGetHash (res : * const MaaResource , buffer : * mut MaaStringBuffer) -> MaaBool) ;
shim ! (MaaResourceGetNodeList (res : * const MaaResource , buffer : * mut MaaStringListBuffer) -> MaaBool) ;
shim ! (MaaResourceGetCustomRecognitionList (res : * const MaaResource , buffer : * mut MaaStringListBuffer) -> MaaBool) ;
shim ! (MaaResourceGetCustomActionList (res : * const MaaResource , buffer : * mut MaaStringListBuffer) -> MaaBool) ;
shim ! (MaaResourceGetDefaultRecognitionParam (res : * const MaaResource , reco_type : * const :: std :: os :: raw :: c_char , buffer : * mut MaaStringBuffer) -> MaaBool) ;
shim ! (MaaResourceGetDefaultActionParam (res : * const MaaResource , action_type : * const :: std :: os :: raw :: c_char , buffer : * mut MaaStringBuffer) -> MaaBool) ;
shim ! (MaaAdbControllerCreate (adb_path : * const :: std :: os :: raw :: c_char , address : * const :: std :: os :: raw :: c_char , screencap_methods : MaaAdbScreencapMethod , input_methods : MaaAdbInputMethod , config : * const :: std :: os :: raw :: c_char , agent_path : * const :: std :: os :: raw :: c_char) -> * mut MaaController) ;
shim ! (MaaWin32ControllerCreate (hWnd : * mut :: std :: os :: raw :: c_void , screencap_method : MaaWin32ScreencapMethod , mouse_method : MaaWin32InputMethod , keyboard_method : MaaWin32InputMethod) -> * mut MaaController) ;
shim ! (MaaCustomControllerCreate (controller : * mut MaaCustomControllerCallbacks , controller_arg : * mut :: std :: os :: raw :: c_void) -> * mut MaaController) ;
shim ! (MaaDbgControllerCreate (read_path : * const :: std :: os :: raw :: c_char , write_path : * const :: std :: os :: raw :: c_char , type_ : MaaDbgControllerType , config : * const :: std :: os :: raw :: c_char) -> * mut MaaController) ;
shim ! (MaaPlayCoverControllerCreate (address : * const :: std :: os :: raw :: c_char , uuid : * const :: std :: os :: raw :: c_char) -> * mut MaaController) ;
shim ! (MaaGamepadControllerCreate (hWnd : * mut :: std :: os :: raw :: c_void , gamepad_type : MaaGamepadType , screencap_method : MaaWin32ScreencapMethod) -> * mut MaaController) ;
shim ! (MaaControllerDestroy (ctrl : * mut MaaController) -> ()) ;
shim ! (MaaControllerAddSink (ctrl : * mut MaaController , sink : MaaEventCallback , trans_arg : * mut :: std :: os :: raw :: c_void) -> MaaSinkId) ;
shim ! (MaaControllerRemoveSink (ctrl : * mut MaaController , sink_id : MaaSinkId) -> ()) ;
shim ! (MaaControllerClearSinks (ctrl : * mut MaaController) -> ()) ;
shim ! (MaaControllerSetOption (ctrl : * mut MaaController , key : MaaCtrlOption , value : MaaOptionValue , val_size : MaaOptionValueSize) -> MaaBool) ;
shim ! (MaaControllerPostConnection (ctrl : * mut MaaController) -> MaaCtrlId) ;
shim ! (MaaControllerPostClick (ctrl : * mut MaaController , x : i32 , y : i32) -> MaaCtrlId) ;
shim ! (MaaControllerPostClickV2 (ctrl : * mut MaaController , x : i32 , y : i32 , contact : i32 , pressure : i32) -> MaaCtrlId) ;
shim ! (MaaControllerPostSwipe (ctrl : * mut MaaController , x1 : i32 , y1 : i32 , x2 : i32 , y2 : i32 , duration : i32) -> MaaCtrlId) ;
shim ! (MaaControllerPostSwipeV2 (ctrl : * mut MaaController , x1 : i32 , y1 : i32 , x2 : i32 , y2 : i32 , duration : i32 , contact : i32 , pressure : i32) -> MaaCtrlId) ;
shim ! (MaaControllerPostClickKey (ctrl : * mut MaaController , keycode : i32) -> MaaCtrlId) ;
shim ! (MaaControllerPostInputText (ctrl : * mut MaaController , text : * const :: std :: os :: raw :: c_char) -> MaaCtrlId) ;
shim ! (MaaControllerPostStartApp (ctrl : * mut MaaController , intent : * const :: std :: os :: raw :: c_char) -> MaaCtrlId) ;
shim ! (MaaControllerPostStopApp (ctrl : * mut MaaController , intent : * const :: std :: os :: raw :: c_char) -> MaaCtrlId) ;
shim ! (MaaControllerPostTouchDown (ctrl : * mut MaaController , contact : i32 , x : i32 , y : i32 , pressure : i32) -> MaaCtrlId) ;
shim ! (MaaControllerPostTouchMove (ctrl : * mut MaaController , contact : i32 , x : i32 , y : i32 , pressure : i32) -> MaaCtrlId) ;
shim ! (MaaControllerPostTouchUp (ctrl : * mut MaaController , contact : i32) -> MaaCtrlId) ;
shim ! (MaaControllerPostKeyDown (ctrl : * mut MaaController , keycode : i32) -> MaaCtrlId) ;
shim ! (MaaControllerPostKeyUp (ctrl : * mut MaaController , keycode : i32) -> MaaCtrlId) ;
shim ! (MaaControllerPostScreencap (ctrl : * mut MaaController) -> MaaCtrlId) ;
shim ! (MaaControllerPostScroll (ctrl : * mut MaaController , dx : i32 , dy : i32) -> MaaCtrlId) ;
shim ! (MaaControllerPostShell (ctrl : * mut MaaController , cmd : * const :: std :: os :: raw :: c_char , timeout : i64) -> MaaCtrlId) ;
shim ! (MaaControllerGetShellOutput (ctrl : * const MaaController , buffer : * mut MaaStringBuffer) -> MaaBool) ;
shim ! (MaaControllerStatus (ctrl : * const MaaController , id : MaaCtrlId) -> MaaStatus) ;
shim ! (MaaControllerWait (ctrl : * const MaaController , id : MaaCtrlId) -> MaaStatus) ;
shim ! (MaaControllerConnected (ctrl : * const MaaController) -> MaaBool) ;
shim ! (MaaControllerCachedImage (ctrl : * const MaaController , buffer : * mut MaaImageBuffer) -> MaaBool) ;
shim ! (MaaControllerGetUuid (ctrl : * mut MaaController , buffer : * mut MaaStringBuffer) -> MaaBool) ;
shim ! (MaaControllerGetResolution (ctrl : * const MaaController , width : * mut i32 , height : * mut i32) -> MaaBool) ;
shim ! (MaaControllerPostPressKey (ctrl : * mut MaaController , keycode : i32) -> MaaCtrlId) ;
shim ! (MaaContextRunTask (context : * mut MaaContext , entry : * const :: std :: os :: raw :: c_char , pipeline_override : * const :: std :: os :: raw :: c_char) -> MaaTaskId) ;
shim ! (MaaContextRunRecognition (context : * mut MaaContext , entry : * const :: std :: os :: raw :: c_char , pipeline_override : * const :: std :: os :: raw :: c_char , image : * const MaaImageBuffer) -> MaaRecoId) ;
shim ! (MaaContextRunAction (context : * mut MaaContext , entry : * const :: std :: os :: raw :: c_char , pipeline_override : * const :: std :: os :: raw :: c_char , box_ : * const MaaRect , reco_detail : * const :: std :: os :: raw :: c_char) -> MaaActId) ;
shim ! (MaaContextRunRecognitionDirect (context : * mut MaaContext , reco_type : * const :: std :: os :: raw :: c_char , reco_param : * const :: std :: os :: raw :: c_char , image : * const MaaImageBuffer) -> MaaRecoId) ;
shim ! (MaaContextRunActionDirect (context : * mut MaaContext , action_type : * const :: std :: os :: raw :: c_char , action_param : * const :: std :: os :: raw :: c_char , box_ : * const MaaRect , reco_detail : * const :: std :: os :: raw :: c_char) -> MaaActId) ;
shim ! (MaaContextWaitFreezes (context : * mut MaaContext , time : MaaSize , box_ : * const MaaRect , wait_freezes_param : * const :: std :: os :: raw :: c_char) -> MaaBool) ;
shim ! (MaaContextOverridePipeline (context : * mut MaaContext , pipeline_override : * const :: std :: os :: raw :: c_char) -> MaaBool) ;
shim ! (MaaContextOverrideNext (context : * mut MaaContext , node_name : * const :: std :: os :: raw :: c_char , next_list : * const MaaStringListBuffer) -> MaaBool) ;
shim ! (MaaContextOverrideImage (context : * mut MaaContext , image_name : * const :: std :: os :: raw :: c_char , image : * const MaaImageBuffer) -> MaaBool) ;
shim ! (MaaContextGetNodeData (context : * mut MaaContext , node_name : * const :: std :: os :: raw :: c_char , buffer : * mut MaaStringBuffer) -> MaaBool) ;
shim ! (MaaContextGetTaskId (context : * const MaaContext) -> MaaTaskId) ;
shim ! (MaaContextGetTasker (context : * const MaaContext) -> * mut MaaTasker) ;
shim ! (MaaContextClone (context : * const MaaContext) -> * mut MaaContext) ;
shim ! (MaaContextSetAnchor (context : * mut MaaContext , anchor_name : * const :: std :: os :: raw :: c_char , node_name : * const :: std :: os :: raw :: c_char) -> MaaBool) ;
shim ! (MaaContextGetAnchor (context : * mut MaaContext , anchor_name : * const :: std :: os :: raw :: c_char , buffer : * mut MaaStringBuffer) -> MaaBool) ;
shim ! (MaaContextGetHitCount (context : * mut MaaContext , node_name : * const :: std :: os :: raw :: c_char , count : * mut MaaSize) -> MaaBool) ;
shim ! (MaaContextClearHitCount (context : * mut MaaContext , node_name : * const :: std :: os :: raw :: c_char) -> MaaBool) ;
shim ! (MaaGlobalSetOption (key : MaaGlobalOption , value : MaaOptionValue , val_size : MaaOptionValueSize) -> MaaBool) ;
shim ! (MaaGlobalLoadPlugin (library_path : * const :: std :: os :: raw :: c_char) -> MaaBool) ;
shim ! (MaaSetGlobalOption (key : MaaGlobalOption , value : MaaOptionValue , val_size : MaaOptionValueSize) -> MaaBool) ;
shim ! (MaaStringBufferCreate () -> * mut MaaStringBuffer) ;
shim ! (MaaStringBufferDestroy (handle : * mut MaaStringBuffer) -> ()) ;
shim ! (MaaStringBufferIsEmpty (handle : * const MaaStringBuffer) -> MaaBool) ;
shim ! (MaaStringBufferClear (handle : * mut MaaStringBuffer) -> MaaBool) ;
shim ! (MaaStringBufferGet (handle : * const MaaStringBuffer) -> * const :: std :: os :: raw :: c_char) ;
shim ! (MaaStringBufferSize (handle : * const MaaStringBuffer) -> MaaSize) ;
shim ! (MaaStringBufferSet (handle : * mut MaaStringBuffer , str_ : * const :: std :: os :: raw :: c_char) -> MaaBool) ;
shim ! (MaaStringBufferSetEx (handle : * mut MaaStringBuffer , str_ : * const :: std :: os :: raw :: c_char , size : MaaSize) -> MaaBool) ;
shim ! (MaaStringListBufferCreate () -> * mut MaaStringListBuffer) ;
shim ! (MaaStringListBufferDestroy (handle : * mut MaaStringListBuffer) -> ()) ;
shim ! (MaaStringListBufferIsEmpty (handle : * const MaaStringListBuffer) -> MaaBool) ;
shim ! (MaaStringListBufferSize (handle : * const MaaStringListBuffer) -> MaaSize) ;
shim ! (MaaStringListBufferAt (handle : * const MaaStringListBuffer , index : MaaSize) -> * const MaaStringBuffer) ;
shim ! (MaaStringListBufferAppend (handle : * mut MaaStringListBuffer , value : * const MaaStringBuffer) -> MaaBool) ;
shim ! (MaaStringListBufferRemove (handle : * mut MaaStringListBuffer , index : MaaSize) -> MaaBool) ;
shim ! (MaaStringListBufferClear (handle : * mut MaaStringListBuffer) -> MaaBool) ;
shim ! (MaaImageBufferCreate () -> * mut MaaImageBuffer) ;
shim ! (MaaImageBufferDestroy (handle : * mut MaaImageBuffer) -> ()) ;
shim ! (MaaImageBufferIsEmpty (handle : * const MaaImageBuffer) -> MaaBool) ;
shim ! (MaaImageBufferClear (handle : * mut MaaImageBuffer) -> MaaBool) ;
shim ! (MaaImageBufferGetRawData (handle : * const MaaImageBuffer) -> MaaImageRawData) ;
shim ! (MaaImageBufferWidth (handle : * const MaaImageBuffer) -> i32) ;
shim ! (MaaImageBufferHeight (handle : * const MaaImageBuffer) -> i32) ;
shim ! (MaaImageBufferChannels (handle : * const MaaImageBuffer) -> i32) ;
shim ! (MaaImageBufferType (handle : * const MaaImageBuffer) -> i32) ;
shim ! (MaaImageBufferSetRawData (handle : * mut MaaImageBuffer , data : MaaImageRawData , width : i32 , height : i32 , type_ : i32) -> MaaBool) ;
shim ! (MaaImageBufferResize (handle : * mut MaaImageBuffer , width : i32 , height : i32) -> MaaBool) ;
shim ! (MaaImageBufferGetEncoded (handle : * const MaaImageBuffer) -> MaaImageEncodedData) ;
shim ! (MaaImageBufferGetEncodedSize (handle : * const MaaImageBuffer) -> MaaSize) ;
shim ! (MaaImageBufferSetEncoded (handle : * mut MaaImageBuffer , data : MaaImageEncodedData , size : MaaSize) -> MaaBool) ;
shim ! (MaaImageListBufferCreate () -> * mut MaaImageListBuffer) ;
shim ! (MaaImageListBufferDestroy (handle : * mut MaaImageListBuffer) -> ()) ;
shim ! (MaaImageListBufferIsEmpty (handle : * const MaaImageListBuffer) -> MaaBool) ;
shim ! (MaaImageListBufferSize (handle : * const MaaImageListBuffer) -> MaaSize) ;
shim ! (MaaImageListBufferAt (handle : * const MaaImageListBuffer , index : MaaSize) -> * const MaaImageBuffer) ;
shim ! (MaaImageListBufferAppend (handle : * mut MaaImageListBuffer , value : * const MaaImageBuffer) -> MaaBool) ;
shim ! (MaaImageListBufferRemove (handle : * mut MaaImageListBuffer , index : MaaSize) -> MaaBool) ;
shim ! (MaaImageListBufferClear (handle : * mut MaaImageListBuffer) -> MaaBool) ;
shim ! (MaaRectCreate () -> * mut MaaRect) ;
shim ! (MaaRectDestroy (handle : * mut MaaRect) -> ()) ;
shim ! (MaaRectGetX (handle : * const MaaRect) -> i32) ;
shim ! (MaaRectGetY (handle : * const MaaRect) -> i32) ;
shim ! (MaaRectGetW (handle : * const MaaRect) -> i32) ;
shim ! (MaaRectGetH (handle : * const MaaRect) -> i32) ;
shim ! (MaaRectSet (handle : * mut MaaRect , x : i32 , y : i32 , w : i32 , h : i32) -> MaaBool) ;
shim ! (MaaVersion () -> * const :: std :: os :: raw :: c_char) ;
shim ! (MaaAgentClientCreateV2 (identifier : * const MaaStringBuffer) -> * mut MaaAgentClient) ;
shim ! (MaaAgentClientCreateTcp (port : u16) -> * mut MaaAgentClient) ;
shim ! (MaaAgentClientDestroy (client : * mut MaaAgentClient) -> ()) ;
shim ! (MaaAgentClientIdentifier (client : * mut MaaAgentClient , identifier : * mut MaaStringBuffer) -> MaaBool) ;
shim ! (MaaAgentClientBindResource (client : * mut MaaAgentClient , res : * mut MaaResource) -> MaaBool) ;
shim ! (MaaAgentClientRegisterResourceSink (client : * mut MaaAgentClient , res : * mut MaaResource) -> MaaBool) ;
shim ! (MaaAgentClientRegisterControllerSink (client : * mut MaaAgentClient , ctrl : * mut MaaController) -> MaaBool) ;
shim ! (MaaAgentClientRegisterTaskerSink (client : * mut MaaAgentClient , tasker : * mut MaaTasker) -> MaaBool) ;
shim ! (MaaAgentClientConnect (client : * mut MaaAgentClient) -> MaaBool) ;
shim ! (MaaAgentClientDisconnect (client : * mut MaaAgentClient) -> MaaBool) ;
shim ! (MaaAgentClientConnected (client : * mut MaaAgentClient) -> MaaBool) ;
shim ! (MaaAgentClientAlive (client : * mut MaaAgentClient) -> MaaBool) ;
shim ! (MaaAgentClientSetTimeout (client : * mut MaaAgentClient , milliseconds : i64) -> MaaBool) ;
shim ! (MaaAgentClientGetCustomRecognitionList (client : * mut MaaAgentClient , buffer : * mut MaaStringListBuffer) -> MaaBool) ;
shim ! (MaaAgentClientGetCustomActionList (client : * mut MaaAgentClient , buffer : * mut MaaStringListBuffer) -> MaaBool) ;
shim ! (MaaAgentClientCreate () -> * mut MaaAgentClient) ;
shim ! (MaaAgentClientCreateSocket (client : * mut MaaAgentClient , identifier : * mut MaaStringBuffer) -> MaaBool) ;
shim ! (MaaAgentServerRegisterCustomRecognition (name : * const :: std :: os :: raw :: c_char , recognition : MaaCustomRecognitionCallback , trans_arg : * mut :: std :: os :: raw :: c_void) -> MaaBool) ;
shim ! (MaaAgentServerRegisterCustomAction (name : * const :: std :: os :: raw :: c_char , action : MaaCustomActionCallback , trans_arg : * mut :: std :: os :: raw :: c_void) -> MaaBool) ;
shim ! (MaaAgentServerAddResourceSink (sink : MaaEventCallback , trans_arg : * mut :: std :: os :: raw :: c_void) -> MaaSinkId) ;
shim ! (MaaAgentServerAddControllerSink (sink : MaaEventCallback , trans_arg : * mut :: std :: os :: raw :: c_void) -> MaaSinkId) ;
shim ! (MaaAgentServerAddTaskerSink (sink : MaaEventCallback , trans_arg : * mut :: std :: os :: raw :: c_void) -> MaaSinkId) ;
shim ! (MaaAgentServerAddContextSink (sink : MaaEventCallback , trans_arg : * mut :: std :: os :: raw :: c_void) -> MaaSinkId) ;
shim ! (MaaAgentServerStartUp (identifier : * const :: std :: os :: raw :: c_char) -> MaaBool) ;
shim ! (MaaAgentServerShutDown () -> ()) ;
shim ! (MaaAgentServerJoin () -> ()) ;
shim ! (MaaAgentServerDetach () -> ()) ;
shim ! (MaaToolkitAdbDeviceListCreate () -> * mut MaaToolkitAdbDeviceList) ;
shim ! (MaaToolkitAdbDeviceListDestroy (handle : * mut MaaToolkitAdbDeviceList) -> ()) ;
shim ! (MaaToolkitAdbDeviceFind (buffer : * mut MaaToolkitAdbDeviceList) -> MaaBool) ;
shim ! (MaaToolkitAdbDeviceFindSpecified (adb_path : * const :: std :: os :: raw :: c_char , buffer : * mut MaaToolkitAdbDeviceList) -> MaaBool) ;
shim ! (MaaToolkitAdbDeviceListSize (list : * const MaaToolkitAdbDeviceList) -> MaaSize) ;
shim ! (MaaToolkitAdbDeviceListAt (list : * const MaaToolkitAdbDeviceList , index : MaaSize) -> * const MaaToolkitAdbDevice) ;
shim ! (MaaToolkitAdbDeviceGetName (device : * const MaaToolkitAdbDevice) -> * const :: std :: os :: raw :: c_char) ;
shim ! (MaaToolkitAdbDeviceGetAdbPath (device : * const MaaToolkitAdbDevice) -> * const :: std :: os :: raw :: c_char) ;
shim ! (MaaToolkitAdbDeviceGetAddress (device : * const MaaToolkitAdbDevice) -> * const :: std :: os :: raw :: c_char) ;
shim ! (MaaToolkitAdbDeviceGetScreencapMethods (device : * const MaaToolkitAdbDevice) -> MaaAdbScreencapMethod) ;
shim ! (MaaToolkitAdbDeviceGetInputMethods (device : * const MaaToolkitAdbDevice) -> MaaAdbInputMethod) ;
shim ! (MaaToolkitAdbDeviceGetConfig (device : * const MaaToolkitAdbDevice) -> * const :: std :: os :: raw :: c_char) ;
shim ! (MaaToolkitDesktopWindowListCreate () -> * mut MaaToolkitDesktopWindowList) ;
shim ! (MaaToolkitDesktopWindowListDestroy (handle : * mut MaaToolkitDesktopWindowList) -> ()) ;
shim ! (MaaToolkitDesktopWindowFindAll (buffer : * mut MaaToolkitDesktopWindowList) -> MaaBool) ;
shim ! (MaaToolkitDesktopWindowListSize (list : * const MaaToolkitDesktopWindowList) -> MaaSize) ;
shim ! (MaaToolkitDesktopWindowListAt (list : * const MaaToolkitDesktopWindowList , index : MaaSize) -> * const MaaToolkitDesktopWindow) ;
shim ! (MaaToolkitDesktopWindowGetHandle (window : * const MaaToolkitDesktopWindow) -> * mut :: std :: os :: raw :: c_void) ;
shim ! (MaaToolkitDesktopWindowGetClassName (window : * const MaaToolkitDesktopWindow) -> * const :: std :: os :: raw :: c_char) ;
shim ! (MaaToolkitDesktopWindowGetWindowName (window : * const MaaToolkitDesktopWindow) -> * const :: std :: os :: raw :: c_char) ;
shim ! (MaaToolkitConfigInitOption (user_path : * const :: std :: os :: raw :: c_char , default_json : * const :: std :: os :: raw :: c_char) -> MaaBool) ;
